version: "3.4"

services:
  pimvapi:
    container_name: homecontrol
    image: homecontrol
    environment:
      - PORT=5000
    ports:
      - 5000:5000
    build:
      context: .
      dockerfile: Dockerfile